-- AlterTable
ALTER TABLE `user` ADD COLUMN `hashedRt` VARCHAR(191) NULL,
    MODIFY `name` VARCHAR(191) NULL,
    MODIFY `email` VARCHAR(191) NULL,
    MODIFY `password` VARCHAR(191) NULL,
    MODIFY `googleid` VARCHAR(191) NULL;
